name: Deploy to Staging (DreamHost)

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DREAMHOST_SSH_PRIVATE_KEY }}

      - name: Add DreamHost to known_hosts
        run: ssh-keyscan -H ${{ secrets.DREAMHOST_HOST }} >> ~/.ssh/known_hosts

      - name: Add DreamHost remote
        run: git remote add dreamhost ssh://${{ secrets.DREAMHOST_USER }}@${{ secrets.DREAMHOST_HOST }}/~/coprospects.git || true

      - name: Push to DreamHost
        run: git push dreamhost staging --force
