name: Deploy to DreamHost

on:
  push:
    branches:
      - main # Run only on pushes to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DREAMHOST_SSH_PRIVATE_KEY }}

      - name: Add DreamHost to known_hosts
        run: ssh-keyscan -H ${{ secrets.DREAMHOST_HOST }} >> ~/.ssh/known_hosts

      - name: Add DreamHost remote
        # This path MUST match where you created the bare repo on DreamHost
        run: git remote add dreamhost ssh://${{ secrets.DREAMHOST_USER }}@${{ secrets.DREAMHOST_HOST }}/~/coprospects.git

      - name: Push to DreamHost
        run: git push dreamhost main --force